### ISSUE TITLE
Sound.retrieve_preview - Seems to fail when a `/` is used in description

### ISSUE THREAD

**Issue by Canule** [MTG/freesound-python#15]
freesound-python returned the error below when feeding the script a random sound during test.
I assume every returned value with `/` in it will cause such error.

Trigger:
https://www.freesound.org/people/YleArkisto/sounds/351753/

**Error**
```
Traceback (most recent call last):
   sound.retrieve_preview(".",sound.name)
 File "..\freesound.py", line 356, in retrieve_preview
   path
 File "..\freesound.py", line 267, in retrieve
    return urlencode(r.retrieve(url, path))
  File "C:\Python35\lib\urllib\request.py", line 1722, in retrieve
    tfp = open(filename, 'wb')
FileNotFoundError: [Errno 2] No such file or directory: '.\\Lintuja järvellä, nokikana / Coots and other birds on a lake in the spring, display, intense sounds, also red-necked grebe, great crested gr
ebe, water splashing (Fulica altra)
```

**Comment by Bomme** [comment]
Hi @Fr6jDJF 

I believe this is not an issue of the client but of the file system. Probably the file system doesn’t allow a `/` character as part of a file name.

You can avoid the issue by simply replacing the `/` character:

```
sound.name.replace("/", "-")
```
