### ISSUE TITLE
AttributeError: module 'freesound' has no attribute 'FreesoundClient'

### ISSUE THREAD

**Issue by songproducer** [MTG/freesound-python#28]
```
Traceback (most recent call last):
  File "/Users/leotreasure/freesound.py", line 1, in <module>
    import freesound
  File "/Users/leotreasure/freesound.py", line 3, in <module>
    client = freesound.FreesoundClient()
AttributeError: module 'freesound' has no attribute 'FreesoundClient'
```

**Comment by alastair** [comment]
I suspect this error is because the script that you wrote is called 'freesound.py' and when you 'import freesound' it is importing this file instead of the freesound library. Try renaming the file that you created.
