### ISSUE TITLE
RuntimeError: dictionary keys changed during iteration

### ISSUE THREAD

**Issue by luisArandas** [MTG/freesound-python#29]
Hello!

Got this error with the example given by the library with the posted code:

`import numpy as np`
`import freesound as fs`

`client = fs.FreesoundClient()`
`client.set_token("api_key", "token")`

`results = client.text_search(query="dubstep",fields="id,name,previews")`

`for sound in results:`
    `sound.retrieve_preview(".", sound.name + ".mp3")`
    `print(sound.name)`

Error:

`Traceback (most recent call last):
  File "C:\Users\me\Desktop\code\python\pertex\pertex\pertex.py", line 14, in <module>
    for sound in results:
  File "C:\Users\me\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\freesound.py", line 298, in __getitem__
    return Sound(self.results[key], self.client)
  File "C:\Users\me\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\freesound.py", line 202, in __init__
    replace_dashes(json_dict)
  File "C:\Users\me\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\freesound.py", line 200, in replace_dashes
    replace_dashes(v)
  File "C:\Users\me\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\freesound.py", line 195, in replace_dashes
    for k, v in d.items():
RuntimeError: dictionary keys changed during iteration
Press any key to continue . . .`

I am using latest Python 3.8 environment, I guess the problem comes from here. Any quick solution?

Thanks

**Comment by ffont** [comment]
Hi, yeah, looks like it is something that before 3.8 was not raising error. Probably because of [these lines](https://github.com/MTG/freesound-python/blob/36efdf79579eb885473562ed13abad40809ed8b3/freesound.py#L186-L209) :
https://github.com/MTG/freesound-python/blob/36efdf79579eb885473562ed13abad40809ed8b3/freesound.py#L186-L209

In line 195, can you try wrapping `d.items()` in `list(d.items())`?

**Comment by luisArandas** [comment]
Hah! Working, thank you :)

**Comment by ffont** [comment]
Prefect :)
